package com.vesterli.hrdemo.foundation.model.view;

import com.vesterli.hrdemo.foundation.bcbase.ViewObjectImpl;

import com.vesterli.hrdemo.foundation.model.view.common.DepartmentsView;

import java.sql.ResultSet;

import oracle.jbo.Row;
import oracle.jbo.ViewCriteria;
import oracle.jbo.server.ViewRowImpl;
import oracle.jbo.server.ViewRowSetImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Mar 24 14:52:32 CET 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DepartmentsViewImpl extends ViewObjectImpl implements DepartmentsView {
  /**
   * This is the default constructor (do not remove).
   */
  public DepartmentsViewImpl() {
  }

  public void showDeleted() {
    removeViewCriteria("DontShowDeleted");
    executeQuery();
  }
  
  public void dontShowDeleted() {
    ViewCriteria vc = getViewCriteria("DontShowDeleted");
    applyViewCriteria(vc);
    executeQuery();
  }

}

