package com.vesterli.hrdemo.foundation.model.view;

import com.vesterli.hrdemo.foundation.bcbase.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Mar 21 14:45:29 CET 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EmployeesViewImpl extends ViewObjectImpl {
  /**
   * This is the default constructor (do not remove).
   */
  public EmployeesViewImpl() {
  }
}

