package com.vesterli.hrdemo.deptemp.model.view.common;

import oracle.jbo.Row;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Apr 16 11:42:04 CEST 2017
// ---------------------------------------------------------------------
public interface EmployeesVORow extends Row {
  void changeDept(Integer newDeptId);
}

