package com.vesterli.hrdemo.foundation.model.view.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Mar 24 15:04:21 CET 2017
// ---------------------------------------------------------------------
public interface DepartmentsView extends ViewObject {
  void dontShowDeleted();

  void showDeleted();
}

